title: Anyu(Leann) Li # your name (or website title) here
logo: "/images/profile2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/anyuleannli/">View My LinkedIn Profile</a> 
   Skills:
  <br><br>
  Programming: Python, R, Stata
  <br>
  Database: SQL, NoSQL
  <br>
  Algorithm: Linear/Logistic Regression, Decision Tree, Random Forest, Boosted Tree, Lasso/Ridge Regression, Neural Network, K-means Clustering, Support Vector Machine, Natural Language Processing (NLP), PCA 
  <br>
  Visualization: R (ggplot2, ggmap, Shiny), Python (matplotlib, plotly, seaborn, wordcloud), Tableau
  <br>
  Data Cleaning: R (tidyverse, lubridate, data.table), Python (numpy, pandas, nltk, regex, SciPy, genism, scikit-learn)
  <br>
  Other Technical Skills: Adobe Analytics, AWS, A/B Testing, Airflow, Excel, Google Analytics, LaTex, PySpark
  <br>
  Soft Skills: Consulting, Dashboarding, Negotiation, Presentation, Time Mangement  
<br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
