title: Anyu(Leann) Li # your name (or website title) here
logo: "/images/profile_4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>About</b>
  <br>
  I graduated from USC, Marshall School of Business with a MS degree in Business Analytics and UC Berkeley with a BA degree in Economics. I'm specializing in solving data science and analytics issues with technical skills including Python, R, Tableau and SQL. I also had experience in applying machine learning algorithms as well as conducting statistical analysis through hands-on big data projects and delivering presentations to data scientists, non-technical people, and C-level executives.
  <br><br>
  <a href="https://www.linkedin.com/in/anyuleannli/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
